/*
 * Copyright (c) 2013, Bui Nguyen Thang, thang.buinguyen@gmail.com, thangbui.net. All rights reserved.
 * Licensed under the GNU General Public License version 2.0 (GPLv2)
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.thangbui.downloader.ui.quicksearch;

import net.thangbui.downloader.WrapLayout;

import java.awt.*;

public class CategoryPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public  javax.swing.JPanel     LinkPanel2;
    public  javax.swing.JLabel     categoryName;
    public  javax.swing.JLabel     jLabelCategoryIcon;
    private javax.swing.JPanel     jPanelLabel;
    private javax.swing.JSeparator jSeparator1;
    /**
     * Creates new form CategoryPanel
     */
    public CategoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLabel = new javax.swing.JPanel();
        jLabelCategoryIcon = new javax.swing.JLabel();
        categoryName = new javax.swing.JLabel();
        LinkPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabelCategoryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apps.png"))); // NOI18N

        categoryName.setBackground(new java.awt.Color(102, 102, 102));
        categoryName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        categoryName.setForeground(new java.awt.Color(102, 102, 102));
        categoryName.setText("Catergory Name");

        javax.swing.GroupLayout jPanelLabelLayout = new javax.swing.GroupLayout(jPanelLabel);
        jPanelLabel.setLayout(jPanelLabelLayout);
        jPanelLabelLayout.setHorizontalGroup(
                jPanelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLabelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabelCategoryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(categoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelLabelLayout.setVerticalGroup(
                jPanelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelCategoryIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLabelLayout.createSequentialGroup()
                                .addComponent(categoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        LinkPanel2.setMaximumSize(new java.awt.Dimension(1000, 300));
        LinkPanel2.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LinkPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 77, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSeparator1)
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(LinkPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LinkPanel2.setLayout(new WrapLayout(FlowLayout.LEFT));
    }// </editor-fold>//GEN-END:initComponents
    // End of variables declaration//GEN-END:variables
}
