/*
 * Copyright (c) 2013, Bob, . All rights reserved.
 * Licensed under the GNU General Public License version 2.0 (GPLv2)
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.downloader.ui.search;

import java.awt.*;

/**
 * Bob
 */
class DownloadButtonCell extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    public javax.swing.JButton jButtonDownload;

    public DownloadButtonCell() {
        initComponents();
        jButtonDelete.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDownload = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        jButtonDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N
        jButtonDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDownloadMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDownloadMouseExited(evt);
            }
        });

        jButtonDelete.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12)); // NOI18N
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        jButtonDelete.setMargin(new java.awt.Insets(4, 4, 4, 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDownloadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDownloadMouseEntered
        jButtonDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download_hover.png"))); // NOI18N
    }//GEN-LAST:event_jButtonDownloadMouseEntered

    private void jButtonDownloadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDownloadMouseExited
        jButtonDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N
    }//GEN-LAST:event_jButtonDownloadMouseExited
    // End of variables declaration//GEN-END:variables
}
