/*
 * Copyright (c) 2013, Bui Nguyen Thang, thang.buinguyen@gmail.com, thangbui.net. All rights reserved.
 * Licensed under the GNU General Public License version 2.0 (GPLv2)
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
 */

package net.thangbui.downloader.ui.component;

import javax.swing.*;
import java.awt.*;

public class ThreeStatusButton extends javax.swing.JPanel {

    public ImageIcon icon;
    public ImageIcon iconHover;
    public ImageIcon iconSelected;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton;

    /**
     * Creates new form SearchLabel
     */
    public ThreeStatusButton() {
        initComponents();
    }

    public ThreeStatusButton setIconPath(String path) {
        icon = new ImageIcon(getClass().getResource(path));
        setNormal();
        return this;
    }

    public ThreeStatusButton setIconHoverPath(String path) {
        iconHover = new ImageIcon(getClass().getResource(path));
        return this;
    }

    public ThreeStatusButton setIconSelectedPath(String path) {
        iconSelected = new ImageIcon(getClass().getResource(path));
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton = new javax.swing.JButton();

        jButton.setText("jButton1");
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMousePressed(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMouseExited(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMouseEntered

    private void jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMouseExited

    private void jButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMousePressed

    private void jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMouseReleased
    // End of variables declaration//GEN-END:variables

    private void setHover() {
        if (iconHover != null) {
            jButton.setIcon(iconHover);
        }
        jButton.setForeground(new Color(211, 227, 154));
    }

    private void setNormal() {
        if (icon != null) {
            jButton.setIcon(icon);
        }
        jButton.setForeground(Color.BLACK);
    }

    private void setSelected() {
        if (iconSelected != null) {
            jButton.setIcon(iconSelected);
        }
        jButton.setForeground(new Color(239, 239, 239));
    }
}
