/*
 * Copyright (c) 2013, Bui Nguyen Thang, thang.buinguyen@gmail.com, thangbui.net. All rights reserved.
 * Licensed under the GNU General Public License version 2.0 (GPLv2)
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.thangbui.downloader.ui.mydownload;
class ProgressCell extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public  javax.swing.JProgressBar jProgressBar;
    private javax.swing.JProgressBar jProgressBar1;

    /**
     * Creates new form StopResumeCell
     */
    public ProgressCell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar = new javax.swing.JProgressBar();

        setPreferredSize(new java.awt.Dimension(156, 28));
        setLayout(new java.awt.GridBagLayout());

        jProgressBar.setValue(10);
        jProgressBar.setPreferredSize(new java.awt.Dimension(146, 24));
        jProgressBar.setStringPainted(true);
        add(jProgressBar, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    // End of variables declaration//GEN-END:variables
}
